# YOUR PROJECT TITLE

> **Note the following:** 
> 1. This is *not* meant to be an example of an actual **data analysis project**, just an example of how to structure such a project.
> 1. Remember the general advice on structuring and commenting your code
> 1. The `dataproject.py` file includes a function which can be used multiple times in this notebook.

In [1]:
# The DST API wrapper
%pip install git+https://github.com/alemartinello/dstapi

Collecting git+https://github.com/alemartinello/dstapi
  Cloning https://github.com/alemartinello/dstapi to /private/var/folders/lb/2stvshn97wz4m8c3hcpvz9bh0000gn/T/pip-req-build-f522xv5q
  Running command git clone --filter=blob:none --quiet https://github.com/alemartinello/dstapi /private/var/folders/lb/2stvshn97wz4m8c3hcpvz9bh0000gn/T/pip-req-build-f522xv5q
  Resolved https://github.com/alemartinello/dstapi to commit d9eeb5a82cbc70b7d63b2ff44d92632fd77123a4
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from dstapi==0.2) (2.1.4)
Requirement already satisfied: requests in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from dstapi==0.2) (2.31.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from pandas->dstapi==0.2) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from pandas->dstapi==0.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from pandas->dstapi==0.2) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from pandas->dstapi==0.2) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from requests->dstapi==0.2) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from requests->dstapi==0.2) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from requests->dstapi==0.2) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from requests->dstapi==0.2) (2024.2.2)
Requirement already satisfied: six>=1.5 in /Users/agnetenielsen/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->dstapi==0.2) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

Imports and set magics:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
#from matplotlib_venn import venn2
import re

# autoreload modules when code is run
%load_ext autoreload
%autoreload 2

# user written modules
import dataproject

from dstapi import DstApi

# Read and clean data

Importing data, through an API and loading it:

In [3]:
proj=DstApi('FRKM123')

A quick overview of the available data

In [4]:
tabsum = proj.tablesummary(language='en')
display(tabsum)

Table FRKM123: Population projections 2023 by region, age, sex and time
Last update: 2023-06-01T08:00:00

,variable name,# values,First value,First value label,Last value,Last value label,Time variable
0,OMRÅDE,99,101,Copenhagen,851,Aalborg,False
1,ALDER,102,TOT,"Age, total",100-,100 years and over,False
2,KØN,2,M,Men,K,Women,False
3,Tid,28,2023,2023,2050,2050,True

***Clean data***

In [5]:
params = proj._define_base_params(language='en')
params

{'table': 'frkm123',
 'format': 'BULK',
 'lang': 'en',
 'variables': [{'code': 'OMRÅDE', 'values': ['*']},
  {'code': 'ALDER', 'values': ['*']},
  {'code': 'KØN', 'values': ['*']},
  {'code': 'Tid', 'values': ['*']}]}

In [6]:
proj_api=proj.get_data(params=params)
proj_api.head(5)

        OMRÅDE     ALDER    KØN   TID  INDHOLD
0  Fredensborg  19 years  Women  2034      223
1  Fredensborg  19 years    Men  2034      240
2  Fredensborg   2 years  Women  2034      240
3  Fredensborg   2 years    Men  2034      268
4  Fredensborg  20 years  Women  2034      172

Rename variables

In [7]:
proj_api.rename(columns = {'OMRÅDE':'municipality'}, inplace=True)
proj_api.rename(columns = {'ALDER':'age'}, inplace=True)
proj_api.rename(columns = {'KØN':'sex'}, inplace=True)
proj_api.rename(columns = {'TID':'year'}, inplace=True)
proj_api.rename(columns = {'INDHOLD':'population_projection'}, inplace=True)
proj_api.head(5)

  municipality       age    sex  year  population_projection
0  Fredensborg  19 years  Women  2034                    223
1  Fredensborg  19 years    Men  2034                    240
2  Fredensborg   2 years  Women  2034                    240
3  Fredensborg   2 years    Men  2034                    268
4  Fredensborg  20 years  Women  2034                    172

In [8]:
df=pd.DataFrame(proj_api)
df['pop_proj_all'] = ""

df.head(5)

  municipality       age    sex  year  population_projection pop_proj_all
0  Fredensborg  19 years  Women  2034                    223
1  Fredensborg  19 years    Men  2034                    240
2  Fredensborg   2 years  Women  2034                    240
3  Fredensborg   2 years    Men  2034                    268
4  Fredensborg  20 years  Women  2034                    172

Summarize values of population_projection if municipality equals each other, age equals each other and year equals each other.

In [9]:
def sumval(group):
    if len(group)>1:
        return group.sum()
    else:
        return group.values[0]
    
df['pop_proj_all']=df.groupby(['municipality','age','year'])['population_projection'].transform(sumval)
df.head(5)

  municipality       age    sex  year  population_projection  pop_proj_all
0  Fredensborg  19 years  Women  2034                    223           463
1  Fredensborg  19 years    Men  2034                    240           463
2  Fredensborg   2 years  Women  2034                    240           508
3  Fredensborg   2 years    Men  2034                    268           508
4  Fredensborg  20 years  Women  2034                    172           371

In [10]:
df=df[df['sex']!='Men']
df.head(5)

  municipality       age    sex  year  population_projection  pop_proj_all
0  Fredensborg  19 years  Women  2034                    223           463
2  Fredensborg   2 years  Women  2034                    240           508
4  Fredensborg  20 years  Women  2034                    172           371
6  Fredensborg  21 years  Women  2034                    135           290
8  Fredensborg  22 years  Women  2034                    106           237

In [11]:
columns_to_drop=['sex','population_projection']
df=df.drop(columns_to_drop, axis=1)

In [12]:
df.head(5)

  municipality       age  year  pop_proj_all
0  Fredensborg  19 years  2034           463
2  Fredensborg   2 years  2034           508
4  Fredensborg  20 years  2034           371
6  Fredensborg  21 years  2034           290
8  Fredensborg  22 years  2034           237

In [13]:
muni_type=df['municipality'].dtype
age_type=df['age'].dtype
year_type=df['year'].dtype
pop_type=df['pop_proj_all'].dtype
print(muni_type)
print(age_type)
print(year_type)
print(pop_type)

object
object
int64
int64

In [14]:
print(type('age'))

<class 'str'>

In [15]:
df=df[df['age']!='Age, total']

In [16]:
df['age'] = df['age'].str.split(" y").str[0].astype(int)
df.head(5)

  municipality  age  year  pop_proj_all
0  Fredensborg   19  2034           463
2  Fredensborg    2  2034           508
4  Fredensborg   20  2034           371
6  Fredensborg   21  2034           290
8  Fredensborg   22  2034           237

In [17]:
# Define age ranges
age_bins = range(df['age'].min(), df['age'].max() + 11, 10)

# Create labels for the age ranges
labels = [f'{i}-{i+9}' if i != 100 else f'{i}+' for i in age_bins[:-1]]

# Use pd.cut() to sort ages into age ranges
df['age_group'] = pd.cut(df['age'], bins=age_bins, labels=labels, right=False)

# Function to summarize values in 'Value' column for each group
def sumval(group):
    if len(group) > 1:
        return group.sum()
    else:
        return group.values[0]

# Applying the function to create the new column
df['pop_proj_age'] = df.groupby(['municipality', 'age_group', 'year'])['pop_proj_all'].transform(sumval)

print(df)

/var/folders/lb/2stvshn97wz4m8c3hcpvz9bh0000gn/T/ipykernel_74308/887293629.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['pop_proj_age'] = df.groupby(['municipality', 'age_group', 'year'])['pop_proj_all'].transform(sumval)

       municipality  age  year  pop_proj_all age_group  pop_proj_age
0       Fredensborg   19  2034           463     10-19          5270
2       Fredensborg    2  2034           508       0-9          5281
4       Fredensborg   20  2034           371     20-29          2687
6       Fredensborg   21  2034           290     20-29          2687
8       Fredensborg   22  2034           237     20-29          2687
...             ...  ...   ...           ...       ...           ...
565478   Jammerbugt   42  2050           418     40-49          4248
565480   Jammerbugt   43  2050           429     40-49          4248
565482   Jammerbugt   44  2050           425     40-49          4248
565484   Jammerbugt   45  2050           427     40-49          4248
565486   Jammerbugt   46  2050           427     40-49          4248

[279972 rows x 6 columns]

In [25]:
df = df.sort_values(by=['municipality','year','age'])
df.head(5)

       municipality  age  year  pop_proj_all age_group  pop_proj_age
136402     Aabenraa    0  2023           501       0-9          5820
136404     Aabenraa    1  2023           547       0-9          5820
136428     Aabenraa    2  2023           540       0-9          5820
136450     Aabenraa    3  2023           592       0-9          5820
136472     Aabenraa    4  2023           637       0-9          5820
136494     Aabenraa    5  2023           597       0-9          5820
136516     Aabenraa    6  2023           647       0-9          5820
136538     Aabenraa    7  2023           545       0-9          5820
136560     Aabenraa    8  2023           604       0-9          5820
136582     Aabenraa    9  2023           610       0-9          5820
136406     Aabenraa   10  2023           623     10-19          7129
136410     Aabenraa   11  2023           633     10-19          7129
136412     Aabenraa   12  2023           674     10-19          7129
136414     Aabenraa   13  2023           716     10-19          7129
136416     Aabenraa   14  2023           709     10-19          7129
136418     Aabenraa   15  2023           719     10-19          7129
136420     Aabenraa   16  2023           744     10-19          7129
136422     Aabenraa   17  2023           778     10-19          7129
136424     Aabenraa   18  2023           814     10-19          7129
136426     Aabenraa   19  2023           719     10-19          7129
136430     Aabenraa   20  2023           677     20-29          5297
136432     Aabenraa   21  2023           508     20-29          5297
136434     Aabenraa   22  2023           526     20-29          5297
136436     Aabenraa   23  2023           469     20-29          5297
136438     Aabenraa   24  2023           465     20-29          5297
136440     Aabenraa   25  2023           479     20-29          5297
136442     Aabenraa   26  2023           467     20-29          5297
136444     Aabenraa   27  2023           519     20-29          5297
136446     Aabenraa   28  2023           603     20-29          5297
136448     Aabenraa   29  2023           584     20-29          5297
136452     Aabenraa   30  2023           629     30-39          6192
136454     Aabenraa   31  2023           618     30-39          6192
136456     Aabenraa   32  2023           659     30-39          6192
136458     Aabenraa   33  2023           612     30-39          6192
136460     Aabenraa   34  2023           599     30-39          6192
136462     Aabenraa   35  2023           632     30-39          6192
136464     Aabenraa   36  2023           616     30-39          6192
136466     Aabenraa   37  2023           611     30-39          6192
136468     Aabenraa   38  2023           566     30-39          6192
136470     Aabenraa   39  2023           650     30-39          6192
136474     Aabenraa   40  2023           605     40-49          7020
136476     Aabenraa   41  2023           645     40-49          7020
136478     Aabenraa   42  2023           660     40-49          7020
136480     Aabenraa   43  2023           679     40-49          7020
136482     Aabenraa   44  2023           687     40-49          7020
136484     Aabenraa   45  2023           690     40-49          7020
136486     Aabenraa   46  2023           749     40-49          7020
136488     Aabenraa   47  2023           737     40-49          7020
136490     Aabenraa   48  2023           783     40-49          7020
136492     Aabenraa   49  2023           785     40-49          7020

In [26]:
df_unique = df.drop_duplicates(subset=['municipality', 'year', 'pop_proj_age'])
df_unique.head(5)

       municipality  age  year  pop_proj_all age_group  pop_proj_age
136402     Aabenraa    0  2023           501       0-9          5820
136406     Aabenraa   10  2023           623     10-19          7129
136430     Aabenraa   20  2023           677     20-29          5297
136452     Aabenraa   30  2023           629     30-39          6192
136474     Aabenraa   40  2023           605     40-49          7020
136496     Aabenraa   50  2023           780     50-59          8744
136518     Aabenraa   60  2023           830     60-69          8082
136540     Aabenraa   70  2023           772     70-79          7026
136562     Aabenraa   80  2023           527     80-89          3136
136584     Aabenraa   90  2023           134     90-99           550
136408     Aabenraa  100  2023             6      100+             6
300594     Aabenraa    0  2024           487       0-9          5805
300598     Aabenraa   10  2024           616     10-19          7013
300622     Aabenraa   20  2024           639     20-29          5233
300644     Aabenraa   30  2024           600     30-39          6244
300666     Aabenraa   40  2024           651     40-49          6936
300688     Aabenraa   50  2024           788     50-59          8617
300710     Aabenraa   60  2024           924     60-69          8169
300732     Aabenraa   70  2024           764     70-79          7092
300754     Aabenraa   80  2024           514     80-89          3277
300776     Aabenraa   90  2024           123     90-99           550
300600     Aabenraa  100  2024             8      100+             8
529497     Aabenraa    0  2025           497       0-9          5745
529501     Aabenraa   10  2025           616     10-19          6790
529525     Aabenraa   20  2025           670     20-29          5151
529547     Aabenraa   30  2025           634     30-39          6337
529569     Aabenraa   40  2025           575     40-49          6711
529591     Aabenraa   50  2025           779     50-59          8480
529613     Aabenraa   60  2025           890     60-69          8250
530087     Aabenraa   70  2025           705     70-79          7029
530109     Aabenraa   80  2025           565     80-89          3447
530131     Aabenraa   90  2025           138     90-99           562
529503     Aabenraa  100  2025            13      100+            13
259067     Aabenraa    0  2026           511       0-9          5790
259071     Aabenraa   10  2026           564     10-19          6617
259095     Aabenraa   20  2026           640     20-29          5106
259117     Aabenraa   30  2026           575     30-39          6366
259139     Aabenraa   40  2026           624     40-49          6621
259161     Aabenraa   50  2026           742     50-59          8281
259183     Aabenraa   60  2026           938     60-69          8332
259205     Aabenraa   70  2026           777     70-79          7016
259227     Aabenraa   80  2026           613     80-89          3655
259249     Aabenraa   90  2026           138     90-99           583
259073     Aabenraa  100  2026            12      100+            12
412502     Aabenraa    0  2027           528       0-9          5748
412506     Aabenraa   10  2027           674     10-19          6599
412530     Aabenraa   20  2027           610     20-29          5060
412552     Aabenraa   30  2027           554     30-39          6369
412574     Aabenraa   40  2027           637     40-49          6534
412596     Aabenraa   50  2027           745     50-59          8052

In [31]:
columns_to_drop_2=['age','pop_proj_all']
df=df_unique.drop(columns_to_drop_2, axis=1)

In [32]:
df.head(50)

       municipality  year age_group  pop_proj_age
136402     Aabenraa  2023       0-9          5820
136406     Aabenraa  2023     10-19          7129
136430     Aabenraa  2023     20-29          5297
136452     Aabenraa  2023     30-39          6192
136474     Aabenraa  2023     40-49          7020
136496     Aabenraa  2023     50-59          8744
136518     Aabenraa  2023     60-69          8082
136540     Aabenraa  2023     70-79          7026
136562     Aabenraa  2023     80-89          3136
136584     Aabenraa  2023     90-99           550
136408     Aabenraa  2023      100+             6
300594     Aabenraa  2024       0-9          5805
300598     Aabenraa  2024     10-19          7013
300622     Aabenraa  2024     20-29          5233
300644     Aabenraa  2024     30-39          6244
300666     Aabenraa  2024     40-49          6936
300688     Aabenraa  2024     50-59          8617
300710     Aabenraa  2024     60-69          8169
300732     Aabenraa  2024     70-79          7092
300754     Aabenraa  2024     80-89          3277
300776     Aabenraa  2024     90-99           550
300600     Aabenraa  2024      100+             8
529497     Aabenraa  2025       0-9          5745
529501     Aabenraa  2025     10-19          6790
529525     Aabenraa  2025     20-29          5151
529547     Aabenraa  2025     30-39          6337
529569     Aabenraa  2025     40-49          6711
529591     Aabenraa  2025     50-59          8480
529613     Aabenraa  2025     60-69          8250
530087     Aabenraa  2025     70-79          7029
530109     Aabenraa  2025     80-89          3447
530131     Aabenraa  2025     90-99           562
529503     Aabenraa  2025      100+            13
259067     Aabenraa  2026       0-9          5790
259071     Aabenraa  2026     10-19          6617
259095     Aabenraa  2026     20-29          5106
259117     Aabenraa  2026     30-39          6366
259139     Aabenraa  2026     40-49          6621
259161     Aabenraa  2026     50-59          8281
259183     Aabenraa  2026     60-69          8332
259205     Aabenraa  2026     70-79          7016
259227     Aabenraa  2026     80-89          3655
259249     Aabenraa  2026     90-99           583
259073     Aabenraa  2026      100+            12
412502     Aabenraa  2027       0-9          5748
412506     Aabenraa  2027     10-19          6599
412530     Aabenraa  2027     20-29          5060
412552     Aabenraa  2027     30-39          6369
412574     Aabenraa  2027     40-49          6534
412596     Aabenraa  2027     50-59          8052

In [35]:
#Resetting the index:
df.reset_index(inplace = True, drop = True) # Drop old index too
df.rename(columns = {'pop_proj_age':'population_projection'}, inplace=True)
df.head(5)

  municipality  year age_group  population_projection
0     Aabenraa  2023       0-9                   5820
1     Aabenraa  2023     10-19                   7129
2     Aabenraa  2023     20-29                   5297
3     Aabenraa  2023     30-39                   6192
4     Aabenraa  2023     40-49                   7020

## Explore each data set

In order to be able to **explore the raw data**, you may provide **static** and **interactive plots** to show important developments

**Interactive plot** :

In [20]:
def plot_func():
    # Function that operates on data set
    pass

widgets.interact(plot_func, 
    # Let the widget interact with data through plot_func()    
);

interactive(children=(Output(),), _dom_classes=('widget-interact',))

Explain what you see when moving elements of the interactive plot around.

# Merge data sets

Now you create combinations of your loaded data sets. Remember the illustration of a (inner) **merge**:

In [21]:
plt.figure(figsize=(15,7))
v = venn2(subsets = (4, 4, 10), set_labels = ('Data X', 'Data Y'))
v.get_label_by_id('100').set_text('dropped')
v.get_label_by_id('010').set_text('dropped' )
v.get_label_by_id('110').set_text('included')
plt.show()

NameError: name 'venn2' is not defined

Here we are dropping elements from both data set X and data set Y. A left join would keep all observations in data X intact and subset only from Y. 

Make sure that your resulting data sets have the correct number of rows and columns. That is, be clear about which observations are thrown away. 

**Note:** Don't make Venn diagrams in your own data project. It is just for exposition.

# Analysis

To get a quick overview of the data, we show some **summary statistics** on a meaningful aggregation.

MAKE FURTHER ANALYSIS. EXPLAIN THE CODE BRIEFLY AND SUMMARIZE THE RESULTS.

# Conclusion

ADD CONCISE CONLUSION.